version: "3.8"

services:
  loki:
    user: "root"
    container_name: loki_container
    build: ./monitoring/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki/config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - dokploy-network

  promtail:
    user: "root"
    container_name: promtail_container
    build: ./monitoring/promtail
    volumes:
      - /var/log:/var/log
      - ./monitoring/promtail/config.yaml:/etc/promtail/config.yaml
    ports:
      - "9080:9080"
    depends_on:
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://localhost:9080/ready"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - dokploy-network

  grafana:
    user: "root"
    container_name: grafana_container
    build: ./monitoring/grafana
    ports:
      - "3334:3000"
    env_file:
      - .env
    environment:
      - GF_METRICS_USERNAME=${GF_METRICS_USERNAME:-admin}
      - GF_METRICS_PASSWORD=${GF_METRICS_PASSWORD:-admin}
    volumes:
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.equiply-monitoring-grafana.rule=Host(`equiply-monitoring-szxojv-5e9209-62-60-246-35.traefik.me`)
      - traefik.http.routers.equiply-monitoring-grafana.entrypoints=web
      - traefik.http.services.equiply-monitoring-grafana.loadbalancer.server.port=3000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    networks:
      - dokploy-network
    depends_on:
      - grafana
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.equiply-monitoring-prometheus.rule=Host(`equiply-monitoring-szxojv-6076f5-62-60-246-35.traefik.me`)
      - traefik.http.routers.equiply-monitoring-prometheus.entrypoints=web
      - traefik.http.services.equiply-monitoring-prometheus.loadbalancer.server.port=9090

networks:
  dokploy-network:
    external: true

volumes:
  grafana-data:
  loki-data:
  prometheus-data:
